# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_auto_20171101_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerInfo',
        ),
    ]
