# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0004_serverinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfo',
            name='asset',
        ),
        migrations.DeleteModel(
            name='ServerInfo',
        ),
    ]
