# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0007_djangosession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
