# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0014_auto_20171228_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
