# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0019_auto_20171228_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='\u5bc6\u7801'),
        ),
    ]
